# Generated by Django 4.2.30 on 2026-04-20 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ACERVO', '0002_remove_emprestimo_livros_emprestimo_livro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ACERVO.livro'),
        ),
    ]
