# Generated by Django 4.2.30 on 2026-04-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACERVO', '0003_alter_emprestimo_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
