# Generated by Django 4.2.30 on 2026-04-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACERVO', '0004_livro_arquivo_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='renovacoes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
