# Generated by Django 5.2.14 on 2026-05-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACERVO', '0007_livro_capa_livro_valor_alter_emprestimo_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
