# Generated by Django 5.1.5 on 2026-05-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACERVO', '0008_alter_livro_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_ultima_renovacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
