"""
Django settings for BIBLIOTECA_DJANGO project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

# Puxa o .env local apontando para a pasta raiz correta
load_dotenv(os.path.join(BASE_DIR, '.env'))

CHAVE_SECRETA = os.getenv('CHAVE_SECRETA')

# CORRIGIDO: Linhas de MEDIA locais e antigas foram removidas daqui para evitar conflitos.

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = CHAVE_SECRETA

DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    'biblioteca-production-9d24.up.railway.app',
    'localhost',
    '127.0.0.1'
]

CSRF_TRUSTED_ORIGINS = [
    'https://biblioteca-production-9d24.up.railway.app'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth', 
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ACERVO', 
    'bootstrap5', 
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'django.contrib.postgres', 
    'allauth.socialaccount.providers.google',
    'storages', # Perfeito, já incluído!
]

SITE_ID = 1

# Configuração do Google
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BIBLIOTECA_DJANGO.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BIBLIOTECA_DJANGO.wsgi.application'


# Database
if 'DATABASE_URL' not in os.environ:
    raise ValueError("DATABASE_URL não configurada no ambiente!")

DATABASES = {
    'default': dj_database_url.parse(os.environ.get('DATABASE_URL'))
}
DATABASES['default']['CONN_MAX_AGE'] = 600

if '.internal' in os.environ.get('DATABASE_URL', ''):
    DATABASES['default']['OPTIONS'] = {'sslmode': 'disable'}
else:
    DATABASES['default']['OPTIONS'] = {'sslmode': 'prefer'}
    
SOCIALACCOUNT_AUTO_SIGNUP = True
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_EMAIL_REQUIRED = True

ACCOUNT_USERNAME_REQUIRED = False

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True
ACCOUNT_UNIQUE_EMAIL = True

SOCIALACCOUNT_STORE_TOKENS = True
SOCIALACCOUNT_QUERY_EMAIL = True

ACCOUNT_FORMS = {
    'signup': 'ACERVO.forms.CustomSignupForm',
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

DATE_INPUT_FORMATS = ['%d/%m/%Y']


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static & Media Files Cloud Storage Configuration

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Credenciais recebidas dinamicamente do painel da Railway
AWS_ACCESS_KEY_ID = os.getenv('SUPABASE_AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('SUPABASE_AWS_SECRET_ACCESS_KEY')
AWS_S3_ENDPOINT_URL = os.getenv('SUPABASE_S3_ENDPOINT_URL')

AWS_STORAGE_BUCKET_NAME = 'media'
AWS_S3_CUSTOM_DOMAIN = f"anzgdobvjetfufoadsds.supabase.co/storage/v1/object/public/{AWS_STORAGE_BUCKET_NAME}"

# Configurações essenciais para o Supabase Storage
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = False 

# URL pública dinâmica vinda da Railway
MEDIA_URL = os.getenv('SUPABASE_MEDIA_URL')


# Configuração unificada do Django 5.x para Armazenamento
STORAGES = {
    "default": {
        # CORRIGIDO: Agora os uploads do usuário vão 100% para o Supabase
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        # Mantém o WhiteNoise servindo os arquivos de estilo CSS/JS na Railway
        "BACKEND": "whitenoise.storage.StaticFilesStorage",
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

BOOTSTRAP5 = {
    'include_jquery': True, 
}

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"